# Generated by Django 5.0.6 on 2024-07-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_point_latitude_point_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='slug',
        ),
    ]
