# Generated by Django 5.0.6 on 2024-07-12 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_point_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью точки'),
        ),
    ]
